name: CVE Scan 
run-name: Checking dependencies for vulnerabilities

on:
  pull_request:
    branches: ["main", "master"]
  merge_group:
    branches: [ "main", "master" ]
  schedule:
    - cron: '21 6 * * 1'
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

# review the right set of permissions        
permissions:
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Read commit contents
  contents: read 
  # Write security summary on pr
  pull-requests: write 

# Requires setting up Advanced security settings including enabling the Dependency graph option.
jobs:
  dependency-scanner:
    name: Dependency Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          license-check: true
          comment-summary-in-pr: always


  security-summary:
    name: Security Review Summary
    runs-on: ubuntu-latest
    needs: [dependency-scanner]
    if: always()
    steps:
      - name: Create security summary
        run: |
          echo "## 🔒 Dependency Security Review Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Tool | Status | Description |" >> $GITHUB_STEP_SUMMARY
          echo "|------|--------|-------------|" >> $GITHUB_STEP_SUMMARY
          echo "| Dependency Review | ${{ needs.dependency-scanner.result }} | GitHub's dependency review for PRs |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY